#!/bin/bash

EXECUTION_CONTEXT=$(pwd)
source "${EXECUTION_CONTEXT}/helpers/utils"
source "${EXECUTION_CONTEXT}/helpers/initial-checks"
source "${EXECUTION_CONTEXT}/helpers/install-vim"

choose_text_editor_to_install() {
  local text_editors=(install_classic_vim install_neovim)
  local text_editor_names=("Vim" "NeoVim")
  local text_editor_array_count=${#text_editors[@]}

  echo "Enter the number to the left of the editor name to install."
  for (( i=0; i<${text_editor_array_count}; i++ )); do 
    echo "${i}: ${text_editor_names[i]}"
  done
  echo
  echo "Input must be a number in the above list"
  echo
  echo -n "> "
  read -r editor 
  echo

  while "true"
  do
    if [[ "$(input_is_number "${editor}")" != "true" ]] ; then
      echo
      echo "Input must be a number in the above list"
      echo
      echo -n "> "
      read -r editor 
    else
      echo "Attempting to install ${text_editor_names[editor]}."
      ${text_editors[${editor}]}
      break;
    fi
  done
}
