#!/bin/bash

EXECUTION_CONTEXT=$(pwd)
source "${EXECUTION_CONTEXT}/helpers/initial-checks"
source "${EXECUTION_CONTEXT}/helpers/choose-text-editor"
# -----------------------Dependencies---------------------
install_ctags
install_ripgrep
install_ack-grep
# --------------------------------------------------------
# check if vim is installed and install if needed
choose_text_editor_to_install

