#!/usr/bin/bash

# check if vim is installed and install if needed

# check if the following directory tree exists and create it if it doesn't
# ~/.vim/
#  - autoload/
#  - backup/
#  - colors/
#  - plugged/

# copy .vimrc config to home directory. If there's one already then rename it, and copy

# check if vim-plug is installed and install if needed

# check if theme list is installed and install if needed


